apiVersion: v1
kind: Pod
metadata:
  name: affinitypod
  labels:
    env: demo
spec:
  containers:
    - image: nginx
      name: nginxaffinity
      ports:
       - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd