apiVersion: apps/v1
kind: Deployment
metadata: 
 labels: 
  env: demo
 name: hpapod
spec:
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      labels: 
        env: demo
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example   
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:   
  labels:
    env: demo
  name: hpasvc
spec:
  ports:
  - targetPort: 80
    port: 80
  selector:
    env: demo