apiVersion: v1
kind: Pod
metadata:
  name: "initpod"
  labels:
    env: dev
spec:
  containers: 
    - name: "demopod"
      image: busybox:1.28
      env:
        - name: sparsh
          value: eren
      command: ['sh', '-c', 'echo the app is running && sleep 3600', ]
  initContainers:
    - name: "initpod"
      image: busybox:1.28
      command: ['sh', '-c', 'until nslookup mysvc.default.svc.cluster.local; do echo waiting for svc to be up; sleep 2; done']