apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    env: dev
spec:
  containers:
  - image: busybox:1.28
    name: liveness
    command: ["/bin/sh", "-c", "touch /tmp/abc; sleep 300; rm -f /tmp/abc; sleep 200;"]
    livenessProbe:
      exec:
        command: ["/bin/sh", "-c", "cat /tmp/abc"]
      initialDelaySeconds: 5
      periodSeconds: 5