apiVersion: v1
kind: Pod
metadata:
  name: affinitypod1
  labels:
    env: demo
spec:
  containers:
    - image: nginx
      name: nginxaffinity1
      ports:
       - containerPort: 80
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: Exists