apiVersion: v1
kind: Pod
metadata:
  labels:
    env: dev
  namespace: mem-example
  name: reqrespod1
spec:
  containers:
  - image: polinux/stress
    name: memory-demo-ctr
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
  