apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset 
  labels:
    env: dev
spec: 
  replicas: 3
  selector:
   matchLabels:
    env: dev
  template:
    metadata:
      name: nginx
      labels:
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

