apiVersion: v1
kind: Service
metadata: 
  name: ns-service
  namespace: demons
  labels:
    env: dev
spec:
  type: ClusterIP 
  selector:
    env: dev  
  ports:
    - port: 80         
      targetPort: 80    